import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server';

export const onRequest = async (context) => {
  const { request, env } = context;
  const url = new URL(request.url);

  // Handle /api/save-chat
  if (url.pathname === '/api/save-chat' && request.method === 'POST') {
    try {
      const { message, sender, model } = await request.json();
      const timestamp = new Date().toISOString();
      await env.DB.prepare(
        'INSERT INTO chat_messages (message, timestamp, sender, model) VALUES (?, ?, ?, ?)'
      )
        .bind(message, timestamp, sender, model || 'unknown')
        .run();
      return new Response('Chat saved', { status: 200 });
    } catch (error) {
      console.error('Error saving chat:', error);
      return new Response('Failed to save chat', { status: 500 });
    }
  }

  // Handle /api/get-chats
  if (url.pathname === '/api/get-chats') {
    try {
      const result = await env.DB.prepare('SELECT * FROM chat_messages ORDER BY timestamp ASC').all();
      return new Response(JSON.stringify(result.results), {
        headers: { 'Content-Type': 'application/json' },
        status: 200,
      });
    } catch (error) {
      console.error('Error fetching chats:', error);
      return new Response('Failed to load chat history', { status: 500 });
    }
  }

  // Pass all other requests to Remix handler
  return createPagesFunctionHandler({
    build: serverBuild as unknown as ServerBuild,
  })(context);
};
