name = "bolt-diy"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"

[build]
command = "pnpm install && pnpm run build"
watch_dir = "app"

[site]
bucket = "build/client"
entry-point = "functions"

[functions]
directory = "functions"
node_compat = true

[pages_build_output]
directory = "build/client"

[[build.upload]]
format = "modules"
main = "functions/[[path]].js"
dir = "build/client"

[env.production]
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]