# wrangler.pages.toml
name = "bolt-diy"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"
output_dir = "./build/client"

[functions]
directory = "./functions"
