#:schema node_modules/wrangler/config-schema.json
name = "bolt-diy"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"

[build]
command = "pnpm install && pnpm run build"

[site]
bucket = "build/client"

send_metrics = false

[functions]
directory = "functions"
node_compat = true

[[build.upload]]
format = "modules"
main = "./functions/[[path]].js"
dir = "build/client"

[[build.external]]
external = ["@remix-run/cloudflare-pages", "@remix-run/cloudflare"]
