#:schema node_modules/wrangler/config-schema.json
name = "bolt-diy"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"

[build]
command = "pnpm install && pnpm run build"
output_directory = "build/client"

[build.upload]
format = "service-worker"

[site]
bucket = "./build/client"

send_metrics = false

[functions]
directory = "functions"
node_compat = true

[[build.external]]
pattern = "@remix-run/cloudflare-pages"

[[build.external]]
pattern = "../build/server"

[[build.external]]
pattern = "../build/server/index.js"
